#!/usr/bin/env node
// Migrates a repository that carries a copy of the project-docs starter (a docs-site/ with its own build
// scripts, components and Bun lockfile, and a 121-line workflow) to the thin shell of @avunu/docusystem
// (section 10.4 of the architecture decision record). Dev-only: it is not in the tarball, and it is deleted
// once the pilots have migrated.
//
//   node scripts/migrate-pilot.mjs <clone> [options]
//
//   <clone>                    the root of a clone of the repository (a folder with .git). The tool works on
//                              the files only: it NEVER runs git. You review `git status`, then commit.
//   --write                    apply the plan. The default is a dry run that changes nothing and lists
//                              every file it would delete, create or update.
//   --diff                     also print the text of every create and update.
//   --site-dir <dir>           the site folder, relative to the clone. Default: docs-site
//   --workflow-sha <sha>       the 40-character commit of the release tag that the two caller workflows are
//                              pinned to: `git ls-remote https://github.com/Avunu/docusystem
//                              'refs/tags/v<version>^{}' refs/tags/v<version>` (the peeled line, else the
//                              plain one). Required with --write; a dry run shows a placeholder.
//   --package-version <x.y.z>  the release being adopted: the `# vX.Y.Z` comment of the pins and the base of
//                              the dependency range. Default: the version in this repository's package.json.
//   --range <range>            the dependency range written to package.json. Default: ^<major>.<minor>.0
//   --json                     print the plan as JSON on stdout (the report goes to stderr).
//
// What it does (steps 1 to 6 of 10.4; step 7, `npm install` and the check, is yours and is printed at the end):
//
//   1. deletes every file of the site folder whose bytes are those of the starter at its last commit
//      (scripts/legacy/starter-v0.json, 83 hashes), the Bun lockfile, project.json when it differs from the
//      starter's only in `name` and `url`, and public/CNAME when it holds the configured domain. A starter
//      file that has been changed is kept and listed.
//   2. turns docs.config.json into docusystem.config.json (same values, `$schema` added).
//   3. writes package.json (one dependency, three scripts), .gitignore and the two caller workflows,
//      replacing the starter's workflow, pinned to --workflow-sha.
//   4. converts the Bun entry of .github/dependabot.yml to npm, in place.
//   5. in dependabot-auto-merge.yml, turns `dependabot/bun/<site>` into `dependabot/npm_and_yarn/<site>`.
//   6. LISTS, and never deletes, what remains: files that differ from the starter's, files the starter never
//      had, formatter and hook settings that mention the site folder, and the advice that needs a person.
//
// It reuses the package's own helpers (the files `docusystem init` writes), from `dist/`: run
// `npm run build` first. Everything is computed before anything is written, and a plan with an error
// writes nothing. Running it again over a migrated clone changes nothing.
//
// Exit codes: 0 the plan was made (and applied with --write); 1 the plan has an error, or a write failed;
// 2 usage error.
import { createHash } from "node:crypto";
import { existsSync, lstatSync, readdirSync, readFileSync, rmdirSync, rmSync } from "node:fs";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { pathToFileURL } from "node:url";
import { parseArgs } from "node:util";
import { canonicalize, canonicalSha256 } from "./legacy/canonical.mjs";

const ROOT = resolve(import.meta.dirname, "..");
export const PACKAGE = "@avunu/docusystem";
export const LEGACY_FILE = join(ROOT, "scripts", "legacy", "starter-v0.json");
/** What a dry run pins the workflows to when no commit is given. */
export const PLACEHOLDER_SHA = "0".repeat(40);
const SCHEMA = "./node_modules/@avunu/docusystem/config.schema.json";
const SCRIPTS = { dev: "docusystem dev", build: "docusystem build", check: "docusystem check" };
const IDENTITY = ["name", "tagline", "slug", "platform", "repo", "domain", "license"];
const CONFIG_KEYS = [...IDENTITY, "branch", "docs", "theme", "images", "jx"];
const WORKFLOWS = ["docs.yml", "docs-publish.yml"];
const WORKFLOW_DIR = ".github/workflows";
/** Files of the starter's template that are the repository's, not the site folder's, or that get special care. */
const SPECIAL = new Set([
  ".github/dependabot.yml",
  ".github/workflows/docs.yml",
  ".gitignore",
  "docs.config.json",
  "package.json",
  "project.json",
  "public/CNAME",
]);
/** The Bun lockfiles: the shell's is package-lock.json. */
const BUN_LOCKS = ["bun.lock", "bun.lockb"];
/** Generated by the starter's postinstall (`jx schema`) and by its build; its .gitignore listed them. */
const GENERATED = ["project.schema.json", "document.schema.json", ".generated"];
/** Never listed as leftovers: installed or built, and ignored by the shell's own .gitignore. */
const IGNORED_DIRS = new Set(["node_modules", "dist", ".docusystem"]);
/** The shell's own files in the site folder. */
const SHELL = new Set([
  "docusystem.config.json",
  "package.json",
  ".gitignore",
  "package-lock.json",
]);

/** The functions this script takes from the package (`dist/lib/*.js`, or `src/lib/*.ts` in the tests). */
export const HELPERS = [
  "applyChanges",
  "dependabotFile",
  "DependabotShapeError",
  "docsPathProblem",
  "ensureDependabotEntries",
  "isAutoMergeWorkflow",
  "patchAutoMerge",
  "readDependabotEntries",
  "readScaffold",
  "renderScaffold",
  "repinWorkflow",
  "siteDirProblem",
  "unifiedDiff",
  "validateConfig",
];

// ---- what the script needs from outside ----

/** The helpers of the modules given, by name; throws naming any that is missing. */
export function pickHelpers(...modules) {
  const found = {};
  for (const name of HELPERS) {
    const module = modules.find((m) => m[name] !== undefined);
    if (module === undefined) throw new Error(`the package modules do not export ${name}`);
    found[name] = module[name];
  }
  return found;
}

/** The helpers as built into this repository's dist/. */
export async function loadHelpers(root = ROOT) {
  const file = (name) => join(root, "dist", "lib", `${name}.js`);
  if (!existsSync(file("workflows"))) {
    throw new Error(
      `${file("workflows")} does not exist: run \`npm run build\` first (this script uses the package's own helpers, as built)`,
    );
  }
  const modules = await Promise.all(
    ["workflows", "dependabot", "automerge", "pin", "config"].map(
      (name) => import(pathToFileURL(file(name)).href),
    ),
  );
  return pickHelpers(...modules);
}

/** The recorded starter (scripts/legacy/starter-v0.json), checked for shape. */
export function loadLegacy(file = LEGACY_FILE) {
  const legacy = JSON.parse(readFileSync(file, "utf8"));
  const hash = /^[0-9a-f]{64}$/;
  const files = legacy.files;
  if (files === null || typeof files !== "object" || Object.keys(files).length === 0) {
    throw new Error(`${file} has no "files"`);
  }
  for (const [path, sha] of Object.entries(files)) {
    if (!hash.test(sha)) throw new Error(`${file}: ${path} has no sha256`);
  }
  for (const name of ["package.json", "project.json"]) {
    const entry = legacy.canonical?.[name];
    if (!Array.isArray(entry?.ignore) || !hash.test(entry?.sha256 ?? "")) {
      throw new Error(`${file}: "canonical" has no usable entry for ${name}`);
    }
  }
  return legacy;
}

/** The version of this repository's package.json. */
export const ownVersion = () =>
  JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")).version;

/** `^0.1.0` for any 0.1.x: the dependency range `docusystem init` writes for a version. */
export function rangeFor(version) {
  const [major = "0", minor = "0"] = version.split(".");
  return `^${Number.parseInt(major, 10)}.${Number.parseInt(minor, 10)}.0`;
}

// ---- reading a clone ----

const sha256File = (path) => createHash("sha256").update(readFileSync(path)).digest("hex");
const lf = (text) => text.replace(/\r\n/g, "\n");

/** `file`, `dir`, `link` or `none`; a link is never followed. */
function kindOf(path) {
  try {
    const stat = lstatSync(path);
    if (stat.isSymbolicLink()) return "link";
    return stat.isDirectory() ? "dir" : "file";
  } catch {
    return "none";
  }
}

const readText = (path) => (kindOf(path) === "file" ? readFileSync(path, "utf8") : null);

/** The parsed JSON of a file, or `{ error }`. */
function readJson(path) {
  try {
    return { value: JSON.parse(readFileSync(path, "utf8")) };
  } catch (error) {
    return { error: error.message };
  }
}

const isRecord = (value) => value !== null && typeof value === "object" && !Array.isArray(value);

/** The key order of `docusystem init`: `$schema`, the seven identity keys, the optional ones; anything else last. */
function configText(values) {
  const ordered = { $schema: typeof values.$schema === "string" ? values.$schema : SCHEMA };
  for (const key of CONFIG_KEYS) if (values[key] !== undefined) ordered[key] = values[key];
  for (const key of Object.keys(values)) if (!(key in ordered)) ordered[key] = values[key];
  return `${JSON.stringify(ordered, null, 2)}\n`;
}

/** Whether two configurations hold the same values (`$schema` and the order of the keys do not count). */
const sameValues = (a, b) => {
  const strip = (config) =>
    JSON.stringify(
      canonicalize(Object.fromEntries(Object.entries(config).filter(([key]) => key !== "$schema"))),
    );
  return strip(a) === strip(b);
};

/** The lines of a text that mention `pattern`, as `{ line, text }`, at most `limit`. */
function mentionsIn(text, pattern, limit = 5) {
  const out = [];
  for (const [at, line] of text.split(/\r?\n/).entries()) {
    if (pattern.test(line)) out.push({ line: at + 1, text: line.trim().slice(0, 160) });
    if (out.length === limit) break;
  }
  return out;
}

const escapeRegExp = (text) => text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/** Root files whose settings may exclude the starter's code from a formatter, a linter or a hook. */
const SETTINGS_FILE =
  /^(?:\.(?:pre-commit-config\.ya?ml|prettierignore|prettierrc.*|eslintignore|eslintrc.*|oxfmtrc.*|oxlintrc.*|editorconfig|gitattributes|gitignore|dockerignore|stylelintignore|markdownlint.*)|package\.json|tsconfig.*\.json|biome\.jsonc?|eslint\.config\..+|prettier\.config\..+|oxlint.*\.json|vitest.*config\..+|vite.*config\..+)$/;

// ---- the plan ----

/**
 * What the migration would do to the clone at `cloneArg`, computed without writing anything.
 *
 * @param {string} cloneArg
 * @param {{ helpers: Record<string, any>, legacy: any, siteDir?: string, version?: string, range?: string, sha?: string }} options
 * @returns the plan: `actions` (`{ kind: "delete" | "create" | "update", path, why, before?, after?, dir? }`,
 *   sorted by path, `path` relative to the clone and `/`-separated), `kept` (`{ path, why }`), `mentions`
 *   (`{ file, lines }`), `advice` (sentences), `errors` (a plan with one writes nothing) and the values used.
 */
export function planMigration(cloneArg, options) {
  const { helpers, legacy } = options;
  const clone = resolve(cloneArg);
  const siteRel = (options.siteDir ?? "docs-site").replace(/^(?:\.\/)+/, "").replace(/\/+$/, "");
  const version = options.version ?? ownVersion();
  const range = options.range ?? rangeFor(version);
  const shaGiven = options.sha !== undefined;
  const sha = options.sha ?? PLACEHOLDER_SHA;
  const plan = {
    clone,
    site: siteRel,
    version,
    range,
    sha,
    shaGiven,
    actions: [],
    kept: [],
    mentions: [],
    advice: [],
    errors: [],
  };
  const error = (message) => plan.errors.push(message);
  const advise = (message) => plan.advice.push(message);

  if (kindOf(clone) !== "dir") {
    error(`${clone} is not a folder`);
    return plan;
  }
  if (kindOf(join(clone, ".git")) === "none") {
    error(`${clone} has no .git: give the root of a clone of the repository`);
    return plan;
  }
  const siteProblem = helpers.siteDirProblem(siteRel);
  if (siteProblem !== null) {
    error(siteProblem);
    return plan;
  }
  const siteAbs = join(clone, ...siteRel.split("/"));
  if (kindOf(siteAbs) !== "dir") {
    error(`${siteRel}/ does not exist in ${clone} (or is a link): nothing to migrate`);
    return plan;
  }
  const at = (rel) => join(siteAbs, ...rel.split("/"));
  const repoAt = (rel) => join(clone, ...rel.split("/"));
  const inSite = (rel) => `${siteRel}/${rel}`;
  const text = (rel) => readText(repoAt(rel));

  const action = (kind, path, why, extra = {}) => plan.actions.push({ kind, path, why, ...extra });
  const planned = new Set(); // repository paths that an action deletes, creates or updates
  const del = (path, why, extra) => {
    planned.add(path);
    action("delete", path, why, extra);
  };
  const put = (path, before, after, why) => {
    planned.add(path);
    if (before === null) action("create", path, why, { before, after });
    else if (before !== after) action("update", path, why, { before, after });
    return before !== after;
  };
  const keep = (path, why) => plan.kept.push({ path, why });

  // ---- the configuration: the values every other step reads ----
  const oldFile = at("docs.config.json");
  const newFile = at("docusystem.config.json");
  const hasOld = kindOf(oldFile) === "file";
  const hasNew = kindOf(newFile) === "file";
  if (!hasOld && !hasNew) {
    error(
      `${siteRel}/ has neither docs.config.json (the starter's) nor docusystem.config.json: this is not a copy of the starter`,
    );
    return plan;
  }
  const read = (file) => readJson(file);
  const oldConfig = hasOld ? read(oldFile) : null;
  const newConfig = hasNew ? read(newFile) : null;
  for (const [name, parsed] of [
    ["docs.config.json", oldConfig],
    ["docusystem.config.json", newConfig],
  ]) {
    if (parsed?.error !== undefined) error(`${inSite(name)} is not valid JSON (${parsed.error})`);
    else if (parsed !== null && !isRecord(parsed.value)) error(`${inSite(name)} is not an object`);
  }
  if (plan.errors.length > 0) return plan;
  const values = (newConfig ?? oldConfig).value;
  if (oldConfig !== null && newConfig !== null && !sameValues(oldConfig.value, newConfig.value)) {
    error(
      `${inSite("docs.config.json")} and ${inSite("docusystem.config.json")} both exist and differ: delete the one that is wrong`,
    );
    return plan;
  }
  const configAfter = configText(values);
  const problems = helpers.validateConfig(JSON.parse(configAfter));
  for (const problem of problems) {
    error(`${inSite("docusystem.config.json")}: ${problem}`);
  }
  if (!hasNew) {
    put(
      inSite("docusystem.config.json"),
      null,
      configAfter,
      `from ${inSite("docs.config.json")}: the same values, $schema added`,
    );
  }
  if (hasOld) del(inSite("docs.config.json"), "converted to docusystem.config.json");

  const slug = typeof values.slug === "string" ? values.slug : "";
  const domain = typeof values.domain === "string" ? values.domain : "";
  const docsSetting = typeof values.docs === "string" ? values.docs : "../docs";
  const docsRel = relative(clone, resolve(siteAbs, docsSetting)).split(sep).join("/");
  if (docsRel.startsWith("..") || isAbsolute(docsRel)) {
    error(
      `the docs folder "${docsSetting}" is outside the repository: files from outside the repository are never published`,
    );
  } else {
    const docsProblem = helpers.docsPathProblem(docsRel);
    if (docsProblem !== null) error(docsProblem);
  }

  // ---- 1. the starter's files ----
  for (const [rel, expected] of Object.entries(legacy.files)) {
    if (SPECIAL.has(rel) || rel.startsWith(".github/")) continue; // the repository's, or handled below
    const path = inSite(rel);
    const kind = kindOf(at(rel));
    if (kind === "none") continue;
    if (kind !== "file") {
      keep(
        path,
        kind === "link"
          ? "a symbolic link: not touched"
          : "a folder where the starter has a file: not touched",
      );
    } else if (sha256File(at(rel)) === expected) {
      del(path, "the starter's file, byte for byte");
    } else {
      keep(
        path,
        "a file of the starter that has been changed: review it, then delete it or carry the change over",
      );
    }
  }
  for (const name of BUN_LOCKS) {
    const kind = kindOf(at(name));
    if (kind === "file") del(inSite(name), "the Bun lockfile: the shell's is package-lock.json");
    else if (kind !== "none") keep(inSite(name), "not a regular file: not touched");
  }

  // project.json: the starter's apart from `name` and `url`, which the shell derives from the config
  if (kindOf(at("project.json")) === "file") {
    const project = read(at("project.json"));
    const wanted = legacy.canonical["project.json"];
    if (project.error !== undefined) {
      keep(inSite("project.json"), `not valid JSON (${project.error}): review it`);
    } else if (
      isRecord(project.value) &&
      canonicalSha256(project.value, wanted.ignore) === wanted.sha256
    ) {
      del(
        inSite("project.json"),
        `the starter's, apart from ${wanted.ignore.join(" and ")} (derived from the config now)`,
      );
    } else {
      keep(
        inSite("project.json"),
        `differs from the starter's beyond ${wanted.ignore.join(" and ")}: carry what you need over as \`theme\` or \`jx\` in docusystem.config.json (or an override), then delete it`,
      );
    }
  } else if (kindOf(at("project.json")) !== "none") {
    keep(inSite("project.json"), "not a regular file: not touched");
  }

  // public/CNAME: generated from the domain now, and a supplied one is an error
  const cnameKind = kindOf(at("public/CNAME"));
  if (cnameKind === "file") {
    const held = readFileSync(at("public/CNAME"), "utf8").trim();
    if (held === domain) del(inSite("public/CNAME"), "the domain, now generated from the config");
    else {
      keep(inSite("public/CNAME"), `holds "${held}", the configured domain is "${domain}"`);
      advise(
        `${inSite("public/CNAME")} must go (the build generates CNAME from \`domain\` and refuses a supplied one): fix \`domain\` in docusystem.config.json if "${held}" is the right one, then delete the file`,
      );
    }
  } else if (cnameKind !== "none") {
    keep(inSite("public/CNAME"), "not a regular file: not touched");
  }

  // ---- 3. package.json, .gitignore and the two callers ----
  const slugged = slug.replaceAll("_", "-");
  const pkgPath = inSite("package.json");
  const pkgBefore = readText(at("package.json"));
  const shellScripts = { ...SCRIPTS };
  const freshPackage = () => ({
    name: `${slugged}-docs`,
    private: true,
    type: "module",
    scripts: shellScripts,
    dependencies: { [PACKAGE]: range },
  });
  if (pkgBefore === null) {
    put(
      pkgPath,
      null,
      `${JSON.stringify(freshPackage(), null, 2)}\n`,
      "one dependency, three scripts",
    );
  } else {
    const parsed = (() => {
      try {
        return JSON.parse(pkgBefore);
      } catch {
        return null;
      }
    })();
    if (!isRecord(parsed)) {
      error(`${pkgPath} is not valid JSON: fix it first`);
    } else {
      const sections = [
        "dependencies",
        "devDependencies",
        "optionalDependencies",
        "peerDependencies",
      ];
      const names = sections.flatMap((s) => (isRecord(parsed[s]) ? Object.keys(parsed[s]) : []));
      const starterLike = isRecord(parsed.scripts) && parsed.scripts.postinstall !== undefined;
      if (starterLike || names.some((n) => n.startsWith("@jxsuite/"))) {
        const exact =
          canonicalSha256(parsed, legacy.canonical["package.json"].ignore) ===
          legacy.canonical["package.json"].sha256;
        put(
          pkgPath,
          pkgBefore,
          `${JSON.stringify(freshPackage(), null, 2)}\n`,
          exact
            ? "the starter's package.json, apart from its name: one dependency, three scripts now"
            : "it differs from the starter's beyond its name: one dependency, three scripts now (what it had is in --diff)",
        );
      } else if (!names.includes(PACKAGE)) {
        // some other package.json: add what the shell needs and keep the rest, as init does
        const next = {
          ...parsed,
          dependencies: {
            ...(isRecord(parsed.dependencies) ? parsed.dependencies : {}),
            [PACKAGE]: range,
          },
          scripts: { ...shellScripts, ...(isRecord(parsed.scripts) ? parsed.scripts : {}) },
        };
        put(
          pkgPath,
          pkgBefore,
          `${JSON.stringify(next, null, 2)}\n`,
          `the dependency and the missing scripts added`,
        );
      }
    }
  }

  const ignorePath = inSite(".gitignore");
  const ignoreBefore = readText(at(".gitignore"));
  const scaffoldIgnore = lf(helpers.readScaffold("gitignore")); // a Windows checkout may have made it CRLF
  if (ignoreBefore === null) {
    put(ignorePath, null, scaffoldIgnore, "node_modules/, dist/, .docusystem/");
  } else if (sha256File(at(".gitignore")) === legacy.files[".gitignore"]) {
    put(
      ignorePath,
      ignoreBefore,
      scaffoldIgnore,
      "the starter's, replaced by the shell's three lines",
    );
  } else {
    const have = new Set(
      ignoreBefore
        .split(/\r?\n/)
        .map((line) => line.trim().replace(/^\//, "").replace(/\/$/, ""))
        .filter((line) => line !== "" && !line.startsWith("#") && !line.startsWith("!")),
    );
    const missing = scaffoldIgnore
      .split("\n")
      .filter((line) => line !== "" && !have.has(line.replace(/\/$/, "")));
    if (missing.length > 0) {
      const base =
        ignoreBefore === "" || ignoreBefore.endsWith("\n") ? ignoreBefore : `${ignoreBefore}\n`;
      put(
        ignorePath,
        ignoreBefore,
        `${base}${missing.join("\n")}\n`,
        `the lines it lacks added (${missing.join(", ")})`,
      );
    }
  }
  // What the starter's postinstall and build left behind is untracked and was ignored by its .gitignore.
  if (ignoreBefore !== null) {
    for (const name of GENERATED) {
      const kind = kindOf(at(name));
      if (kind === "none") continue;
      if (kind === "link") keep(inSite(name), "a symbolic link: not touched");
      else
        del(inSite(name), "generated by the starter's scripts (it was git-ignored)", {
          dir: kind === "dir",
        });
    }
  }

  // The caller workflows. One that is already the caller of the shared workflow, whatever its pin, stays.
  const ANY = PLACEHOLDER_SHA;
  const render = (file, pin, v) => {
    try {
      return helpers.renderScaffold(file, { docs: docsRel, site: siteRel, sha: pin, version: v });
    } catch (renderError) {
      error(renderError.message);
      return null;
    }
  };
  for (const file of WORKFLOWS) {
    const path = `${WORKFLOW_DIR}/${file}`;
    const before = text(path);
    const wanted = render(file, sha, version);
    const generic = render(file, ANY, "0.0.0");
    if (wanted === null || generic === null) continue;
    const already =
      before !== null && lf(helpers.repinWorkflow(before, ANY, "0.0.0") ?? before) === lf(generic);
    if (already) continue;
    let why = "the caller of the shared workflow";
    if (before !== null) {
      const lines = before.split("\n").length - (before.endsWith("\n") ? 1 : 0);
      why =
        file === "docs.yml" &&
        sha256File(repoAt(path)) === legacy.files[".github/workflows/docs.yml"]
          ? `the starter's ${lines}-line workflow, replaced by the caller of the shared workflow`
          : `replaced by the caller of the shared workflow (it is not the starter's: ${lines} lines, see --diff)`;
    }
    put(path, before, wanted, why);
  }
  if (!shaGiven) {
    advise(
      `the callers are pinned to the placeholder commit ${PLACEHOLDER_SHA}: --write needs --workflow-sha <the commit of the tag v${version}> (git ls-remote https://github.com/Avunu/docusystem 'refs/tags/v${version}^{}' refs/tags/v${version})`,
    );
  }

  // ---- 4. Dependabot ----
  const dependabotPath = helpers.dependabotFile(clone);
  const dependabotBefore = text(dependabotPath);
  try {
    const next = helpers.ensureDependabotEntries(dependabotBefore, {
      site: siteRel,
      actions: true,
    });
    if (next.text !== dependabotBefore) {
      put(dependabotPath, dependabotBefore, next.text, next.changes.join("; "));
    }
    for (const entry of helpers.readDependabotEntries(next.text).entries) {
      if (!entry.cooldown.present) continue;
      if (
        entry.ecosystem === "npm" &&
        entry.directories.includes(`/${siteRel}`) &&
        !entry.cooldown.excludes.includes(PACKAGE)
      ) {
        advise(
          `${dependabotPath}: the npm entry for /${siteRel} has a cooldown that does not exclude "${PACKAGE}" (releases of the package would wait for it): add \`exclude: ["${PACKAGE}"]\` under its cooldown`,
        );
      }
      if (
        entry.ecosystem === "github-actions" &&
        entry.directories.includes("/") &&
        !entry.cooldown.excludes.includes("Avunu/docusystem")
      ) {
        advise(
          `${dependabotPath}: the github-actions entry has a cooldown that does not exclude Avunu/docusystem (a new release of the shared workflows would wait for it): add \`exclude: ["Avunu/docusystem"]\` under its cooldown`,
        );
      }
    }
    const bun = mentionsIn(next.text, /\bbun\b/i);
    if (bun.length > 0) {
      advise(
        `${dependabotPath} still says "Bun" in a comment (${bun.map((m) => `line ${m.line}`).join(", ")}): the site's packages are npm's now, reword it`,
      );
    }
  } catch (shapeError) {
    if (!(shapeError instanceof helpers.DependabotShapeError)) throw shapeError;
    advise(
      `${dependabotPath} ${shapeError.message}; add this to its \`updates:\` list by hand:\n${shapeError.snippet.trimEnd()}`,
    );
  }

  // ---- 5. the auto-merge workflow ----
  const workflowDir = repoAt(WORKFLOW_DIR);
  const workflowFiles =
    kindOf(workflowDir) === "dir"
      ? readdirSync(workflowDir)
          .filter((f) => /\.ya?ml$/.test(f))
          .sort()
      : [];
  for (const file of workflowFiles) {
    if (WORKFLOWS.includes(file)) continue;
    const path = `${WORKFLOW_DIR}/${file}`;
    const before = text(path);
    if (before === null || !helpers.isAutoMergeWorkflow(before)) continue;
    const patched = helpers.patchAutoMerge(before, siteRel);
    if (patched.changed) {
      put(
        path,
        before,
        patched.text,
        `${siteRel}/ updates and the shared workflows' pin now wait for a person`,
      );
    }
    if (patched.note !== undefined) advise(`${path}: ${patched.note}`);
  }

  // ---- 6. what remains: listed, never deleted ----
  const shown = new Set(plan.kept.map((k) => k.path));
  const walk = (dir, prefix) => {
    for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
      a.name < b.name ? -1 : 1,
    )) {
      const rel = `${prefix}${entry.name}`;
      const path = inSite(rel);
      if (prefix === "" && (IGNORED_DIRS.has(entry.name) || SHELL.has(entry.name))) continue;
      if (planned.has(path) || shown.has(path)) continue;
      if (entry.isSymbolicLink()) {
        keep(path, "a symbolic link: not touched");
      } else if (entry.isDirectory()) {
        walk(join(dir, entry.name), `${rel}/`);
      } else if (legacy.files[rel] !== undefined) {
        continue; // a file of the starter: deleted, or already reported above
      } else if (rel.startsWith("public/") || rel.startsWith("overrides/")) {
        keep(
          path,
          "not a starter file; public/ and overrides/ are the shell's own folders, so it stays",
        );
      } else {
        keep(
          path,
          "not a starter file: the shell has no use for it here (doctor reports leftovers); review it",
        );
      }
    }
  };
  walk(siteAbs, "");

  // Settings that exist for the starter's code: a formatter or hook excluding docs-site/.
  // the folder's name as a path of its own: not part of a longer name, not below another folder (but `**/docs-site` is)
  const mention = new RegExp(`(?:^|[^\\w/-]|\\*\\*/)${escapeRegExp(siteRel)}(?![\\w-])`);
  const candidates = [
    ...readdirSync(clone).filter((f) => SETTINGS_FILE.test(f) && kindOf(repoAt(f)) === "file"),
    ...workflowFiles.filter((f) => !WORKFLOWS.includes(f)).map((f) => `${WORKFLOW_DIR}/${f}`),
  ].sort();
  for (const file of candidates) {
    const content = readText(repoAt(file)) ?? "";
    if (planned.has(file) || helpers.isAutoMergeWorkflow(content)) continue; // the auto-merge workflow names the site on purpose
    const lines = mentionsIn(content, mention);
    if (lines.length > 0) plan.mentions.push({ file, lines });
  }
  if (plan.mentions.length > 0) {
    advise(
      `${plan.mentions.map((m) => m.file).join(", ")} ${plan.mentions.length === 1 ? "mentions" : "mention"} ${siteRel}/: remove an ignore that existed only for the starter's code (it has none now), and keep a docs/ exclusion for a hook that stamps a copyright comment above front matter; \`docusystem doctor\` re-checks`,
    );
  }
  if (kindOf(at("node_modules")) === "dir") {
    advise(
      `${siteRel}/node_modules exists (installed by Bun): remove it before \`npm install\` so that npm does not reconcile Bun's layout`,
    );
  }

  for (const a of plan.actions) {
    const problem = plainProblem(clone, a.path);
    if (problem !== null) error(problem);
  }

  plan.actions.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  plan.kept.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  return plan;
}

// ---- applying a plan ----

/**
 * Why `path` (relative to the clone) must not be written or deleted: it is outside the clone, or is, or
 * lies below, a symbolic link (the real-bytes rule: a link committed to a repository must not make this
 * tool touch a file somewhere else). Null when it may be touched.
 */
function plainProblem(clone, path) {
  const target = resolve(clone, path);
  const parts = relative(clone, target).split(sep);
  if (parts[0] === ".." || isAbsolute(parts[0])) {
    return `refusing to touch ${path}: it is not inside ${clone}`;
  }
  let at = clone;
  for (const part of parts) {
    at = join(at, part);
    const kind = kindOf(at);
    if (kind === "link") return `refusing to touch ${path}: ${part} is a symbolic link`;
    if (kind === "none") break;
  }
  return null;
}

/**
 * Writes the plan: the creates and updates first (all or nothing as far as it can tell beforehand: a path
 * through a symbolic link is refused before anything is written), then the deletions, then the folders
 * the deletions emptied. Throws when the plan has errors.
 */
export function applyPlan(plan, helpers) {
  if (plan.errors.length > 0) throw new Error("the plan has errors; nothing is written");
  const deletions = plan.actions.filter((a) => a.kind === "delete");
  for (const a of plan.actions) {
    const problem = plainProblem(plan.clone, a.path);
    if (problem !== null) throw new Error(problem);
  }
  helpers.applyChanges(
    plan.clone,
    plan.actions
      .filter((a) => a.kind !== "delete")
      .map((a) => ({ path: a.path, action: a.kind, before: a.before ?? null, after: a.after })),
  );
  const site = join(plan.clone, ...plan.site.split("/"));
  for (const a of deletions) {
    const file = resolve(plan.clone, a.path);
    rmSync(file, { recursive: a.dir === true, force: true });
    for (
      let dir = dirname(file);
      dir !== site && dir.startsWith(`${site}${sep}`);
      dir = dirname(dir)
    ) {
      if (kindOf(dir) !== "dir" || readdirSync(dir).length > 0) break;
      rmdirSync(dir);
    }
  }
}

// ---- the report ----

/** Counts of the actions of a plan. */
export function summarize(plan) {
  const count = (kind) => plan.actions.filter((a) => a.kind === kind).length;
  return {
    delete: count("delete"),
    update: count("update"),
    create: count("create"),
    kept: plan.kept.length,
  };
}

/** The report as lines of text. */
export function formatPlan(plan, o = {}) {
  const lines = [];
  const { write = false, diff = false, unifiedDiff } = o;
  const s = summarize(plan);
  lines.push(
    `migrate-pilot: ${plan.clone} (site folder ${plan.site}/, @avunu/docusystem ${plan.range}, pins v${plan.version})`,
  );
  lines.push(
    plan.errors.length > 0
      ? "migrate-pilot: the plan has an error: nothing is written"
      : write
        ? "migrate-pilot: applying the plan"
        : "migrate-pilot: dry run: nothing is written; add --write to apply the plan",
  );
  if (plan.errors.length > 0) {
    lines.push("", "Errors (the plan is not applied while there is one):");
    for (const e of plan.errors) lines.push(`  - ${e}`);
  }
  if (plan.actions.length === 0) {
    if (plan.errors.length === 0) lines.push("", "Nothing to do: the clone is already migrated.");
  } else {
    lines.push("");
    const width = Math.max(...plan.actions.map((a) => a.path.length));
    for (const a of plan.actions) {
      lines.push(`  ${a.kind.padEnd(6)}  ${a.path.padEnd(width)}  ${a.why}`);
    }
    lines.push("", `  ${s.delete} to delete, ${s.update} to update, ${s.create} to create`);
  }
  if (diff && unifiedDiff !== undefined) {
    for (const a of plan.actions.filter((x) => x.kind !== "delete")) {
      lines.push("", ...unifiedDiff(a.path, a.before ?? null, a.after));
    }
  }
  if (plan.kept.length > 0) {
    lines.push(
      "",
      "Kept, for a person to look at (they differ from the starter, or are not the starter's):",
    );
    for (const k of plan.kept) lines.push(`  ${k.path}: ${k.why}`);
  }
  if (plan.mentions.length > 0) {
    lines.push("", `Settings that mention ${plan.site}/:`);
    for (const m of plan.mentions) {
      for (const l of m.lines) lines.push(`  ${m.file}:${l.line}: ${l.text}`);
    }
  }
  if (plan.advice.length > 0) {
    lines.push("", "For you to do by hand:");
    for (const a of plan.advice) {
      const [first = "", ...rest] = a.split("\n");
      lines.push(`  - ${first}`);
      for (const line of rest) lines.push(`    ${line}`);
    }
  }
  if (plan.errors.length === 0 && plan.actions.length > 0 && write) {
    lines.push(
      "",
      "Next:",
      `  cd ${plan.site} && npm install && CI=true npm run check && npx docusystem doctor`,
      "  then review `git status` and `git diff`, and commit as one commit:",
      "  docs: build the documentation site with @avunu/docusystem",
    );
  } else if (plan.errors.length === 0 && plan.actions.length > 0) {
    lines.push("", "Run again with --write to apply it.");
  }
  return lines;
}

// ---- the command line ----

const USAGE =
  "usage: node scripts/migrate-pilot.mjs <clone> [--write] [--diff] [--site-dir <dir>] [--workflow-sha <sha>]\n" +
  "         [--package-version <x.y.z>] [--range <range>] [--json]";

/** Parses and validates the command line; returns `{ error }` for a usage error. */
export function parseOptions(argv) {
  let parsed;
  try {
    parsed = parseArgs({
      args: argv,
      allowPositionals: true,
      options: {
        write: { type: "boolean" },
        diff: { type: "boolean" },
        "site-dir": { type: "string" },
        "workflow-sha": { type: "string" },
        "package-version": { type: "string" },
        range: { type: "string" },
        json: { type: "boolean" },
        help: { type: "boolean", short: "h" },
      },
    });
  } catch (e) {
    return { error: e.message };
  }
  const v = parsed.values;
  if (v.help) return { help: true };
  if (parsed.positionals.length !== 1) return { error: "give the clone to migrate (one folder)" };
  const sha = v["workflow-sha"]?.toLowerCase();
  if (sha !== undefined && !/^[0-9a-f]{40}$/.test(sha)) {
    return {
      error: `--workflow-sha must be a full 40-character commit id (got "${v["workflow-sha"]}")`,
    };
  }
  if (v.write && sha === undefined) {
    return {
      error:
        "--write needs --workflow-sha <commit>: the callers are pinned to the commit of the release tag (this script runs no git; `git ls-remote https://github.com/Avunu/docusystem 'refs/tags/v<version>^{}' refs/tags/v<version>` prints it)",
    };
  }
  const version = v["package-version"];
  if (version !== undefined && !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(version)) {
    return { error: `--package-version must be MAJOR.MINOR.PATCH (got "${version}")` };
  }
  return {
    clone: parsed.positionals[0],
    write: v.write === true,
    diff: v.diff === true,
    siteDir: v["site-dir"],
    sha,
    version,
    range: v.range,
    json: v.json === true,
  };
}

async function main(argv) {
  const options = parseOptions(argv);
  if (options.help) {
    console.log(USAGE);
    return 0;
  }
  if (options.error) {
    console.error(`migrate-pilot: ${options.error}\n${USAGE}`);
    return 2;
  }
  let helpers;
  let legacy;
  try {
    helpers = await loadHelpers();
    legacy = loadLegacy();
  } catch (e) {
    console.error(`migrate-pilot: ${e.message}`);
    return 1;
  }
  const plan = planMigration(options.clone, {
    helpers,
    legacy,
    siteDir: options.siteDir,
    version: options.version,
    range: options.range,
    sha: options.sha,
  });
  const log = options.json ? console.error : console.log;
  for (const line of formatPlan(plan, {
    write: options.write,
    diff: options.diff,
    unifiedDiff: helpers.unifiedDiff,
  })) {
    log(line);
  }
  if (options.json) {
    const { clone, site, version, range, sha, shaGiven, actions, kept, mentions, advice, errors } =
      plan;
    console.log(
      JSON.stringify(
        {
          clone,
          site,
          version,
          range,
          sha,
          shaGiven,
          summary: summarize(plan),
          actions: actions.map(({ kind, path, why }) => ({ kind, path, why })),
          kept,
          mentions,
          advice,
          errors,
        },
        null,
        2,
      ),
    );
  }
  if (plan.errors.length > 0) return 1;
  if (options.write) {
    try {
      applyPlan(plan, helpers);
    } catch (e) {
      console.error(`migrate-pilot: ${e.message}`);
      return 1;
    }
    log(
      `migrate-pilot: wrote ${plan.actions.length} change${plan.actions.length === 1 ? "" : "s"}`,
    );
  }
  return 0;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  process.exitCode = await main(process.argv.slice(2));
}
